name: Test Sprint creation

on:
  schedule:
    - cron: '45 18 * * 0'  # Schedule it to run at midnight every Sunday (adjust the schedule as needed)
  workflow_dispatch:  

jobs:
  create_sprint_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run shell script
      run: |
        chmod +x create_sprint_branch.sh  # Ensure the script is executable
        ./create_sprint_branch.sh  # Run the shell script
