name: Create Sprint Branch

on:
  schedule:
    - cron: '20 18 * * *'
  workflow_dispatch:
jobs:
  create_sprint_branch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Run Python script
      run: |
        python create_sprint_branch.py  # Replace with the actual filename if different
